# Generated by Django 5.0 on 2024-02-20 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='https://twitter.com', null=True)),
                ('text', models.CharField(blank=True, default='', null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('impressions', models.IntegerField(blank=True, default=0, null=True)),
                ('engagements', models.IntegerField(blank=True, default=0, null=True)),
                ('engagement_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('retweets', models.IntegerField(blank=True, default=0, null=True)),
                ('replies', models.IntegerField(blank=True, default=0, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('norm_score', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('profile_clicks', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
