# Generated by Django 5.0 on 2024-02-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default='https://twitter.com', null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('norm_score', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
