# Generated by Django 5.0 on 2024-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='user',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
