# Generated by Django 5.0 on 2024-03-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_keywords_user_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='username',
        ),
    ]
