# Generated by Django 5.0 on 2024-07-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threads_id', models.IntegerField(blank=True, default=0, null=True)),
                ('username', models.CharField(default='', null=True, unique=True)),
                ('biography', models.CharField(blank=True, default='', null=True)),
                ('profile_pic_url', models.CharField(blank=True, default='', null=True)),
                ('followers', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
