# Generated by Django 5.0 on 2024-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_threadsprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadsprofile',
            name='threads_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
