# Generated by Django 5.0 on 2024-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_threadsprofile_threads_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadsprofile',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='threadsprofile',
            name='replies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
