# Generated by Django 5.0 on 2024-07-19 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_threadsprofile_likes_threadsprofile_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', null=True)),
                ('url', models.CharField(blank=True, default='', null=True)),
                ('text', models.CharField(blank=True, default='', null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('short_code', models.CharField(blank=True, default='', null=True)),
                ('threadid', models.IntegerField(blank=True, default=0, null=True)),
                ('is_quote', models.BooleanField(blank=True, default=False, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('engagement_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('reposts', models.IntegerField(blank=True, default=0, null=True)),
                ('replies', models.IntegerField(blank=True, default=0, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('quotes', models.IntegerField(blank=True, default=0, null=True)),
                ('norm_score', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
