# Generated by Django 5.0 on 2024-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='threadid',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
