# Generated by Django 5.0 on 2024-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_thread_threadid'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', null=True)),
                ('word', models.CharField(blank=True, default='https://twitter.com', null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('norm_score', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
