# Generated by Django 5.0 on 2024-07-25 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_keywordsthreads'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadsprofile',
            name='profile_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 21, 29, 97730)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='norm_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
