# Generated by Django 5.0 on 2024-07-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_threadsprofile_profile_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadsprofile',
            name='profile_last_update',
        ),
    ]
