# Generated by Django 5.0 on 2024-07-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_threadsprofile_profile_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadsprofile',
            name='quotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='threadsprofile',
            name='reposts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
