# Generated by Django 5.0 on 2024-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_threadsprofile_quotes_threadsprofile_reposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsthreads',
            name='norm_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='keywordsthreads',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
