# Generated by Django 5.0 on 2024-08-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_keywordsthreads_norm_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadsprofile',
            name='name',
            field=models.CharField(default='', null=True),
        ),
    ]
