# Generated by Django 5.0 on 2024-03-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='First Name'),
        ),
    ]
