# Generated by Django 5.2.8 on 2025-11-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=0, verbose_name='User credits'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_collation='NOCASE', error_messages={'unique': 'A user with such email already exists'}, max_length=255),
        ),
    ]
