# Generated by Django 5.0 on 2024-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_collation='und-x-icu', error_messages={'unique': 'A user with such email already exists'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Twitter Username'),
        ),
    ]
