# Generated by Django 5.0 on 2024-03-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Designates whether the user has paid his subscription', verbose_name='Paid User'),
        ),
    ]
