# Generated by Django 5.0 on 2024-03-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0005_user_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Designates whether the topics for this user have been analyzed', verbose_name='Topics Processed'),
        ),
    ]
