# Generated by Django 5.0 on 2024-07-11 09:23

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0006_user_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_threads',
            field=models.BooleanField(default=False, help_text='Connected to Threads profile', verbose_name='Threads Connected'),
        ),
        migrations.AddField(
            model_name='user',
            name='threads_token',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
        ),
    ]
