# Generated by Django 5.0 on 2024-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0007_user_has_threads_user_threads_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='threads_username',
            field=models.CharField(default='', max_length=50, verbose_name='Threads Username'),
        ),
    ]
