# Generated by Django 5.0 on 2024-07-23 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0008_user_threads_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 8, 57, 28, 499365), verbose_name='Last updated Threads Topics analysis'),
        ),
    ]
