# Generated by Django 5.0 on 2024-07-24 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0009_user_threads_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 59, 13, 847471), verbose_name='Last updated Threads Profile stats'),
        ),
        migrations.AlterField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 59, 13, 847395), verbose_name='Last updated Threads Topics analysis'),
        ),
    ]
