# Generated by Django 5.0 on 2024-07-25 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0010_user_profile_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_last_update',
        ),
        migrations.AlterField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 21, 29, 88651), verbose_name='Last updated Threads Topics analysis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
