# Generated by Django 5.0 on 2024-07-25 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0011_remove_user_profile_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 37, 55, 446020), verbose_name='Last updated Threads Topics analysis'),
        ),
    ]
