# Generated by Django 5.0 on 2024-07-25 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0012_alter_user_threads_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 51, 48, 24627), verbose_name='Last updated Threads Profile stats'),
        ),
        migrations.AlterField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 51, 48, 24509), verbose_name='Last updated Threads Topics analysis'),
        ),
    ]
