# Generated by Django 5.0 on 2024-07-25 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0013_user_profile_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 52, 8, 953854), verbose_name='Last updated Threads Profile stats'),
        ),
        migrations.AlterField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 52, 8, 953772), verbose_name='Last updated Threads Topics analysis'),
        ),
    ]
