# Generated by Django 5.0 on 2024-07-29 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0014_alter_user_profile_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_free_trial',
            field=models.BooleanField(default=True, verbose_name='Free Trial'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 14, 11, 52, 59302), verbose_name='Last updated Threads Profile stats'),
        ),
        migrations.AlterField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 14, 11, 52, 59226), verbose_name='Last updated Threads Topics analysis'),
        ),
    ]
