# Generated by Django 5.0 on 2024-08-22 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0017_alter_user_profile_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 42, 13, 879906), verbose_name='Last updated Threads Profile stats'),
        ),
        migrations.AlterField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 42, 13, 879818), verbose_name='Last updated Threads Topics analysis'),
        ),
    ]
