# Generated by Django 5.1.7 on 2025-04-02 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0018_alter_user_profile_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 17, 36, 12, 799231), verbose_name='Last updated Threads Profile stats'),
        ),
        migrations.AlterField(
            model_name='user',
            name='threads_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 17, 36, 12, 799184), verbose_name='Last updated Threads Topics analysis'),
        ),
    ]
